name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Init Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Load cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local # the path depends on the OS
          key: poetry-0 # increment to reset cache

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Code Quality
        run: poetry run black . --check

      - name: Test using pytest
        run: poetry run pytest --cov . -n 2
